[package]
name = "peacock-fuzz"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
debug = true
panic = "abort"

[dependencies]
serde_json = { version = "1.0", features = ["default", "preserve_order"] }
json_comments = "0.2"
thiserror = "1.0"
ahash = { version = "0.8", default-features = false, features = ["std", "compile-time-rng"] }
petgraph = "0.6"

# Needed for binaries
clap = { version = "4.4", features = ["derive"] }
libloading = "0.8"
serde = "1.0"
libafl = "0.11"
libafl_bolts = "0.11"
nix = "0.26"

[[bin]]
name = "peacock-dump"
path = "src/bin/dump.rs"

[[bin]]
name = "peacock-fuzz"
path = "src/bin/peacock.rs"

[[bin]]
name = "peacock-gen"
path = "src/bin/generate.rs"
